// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqV-v1svhYUDRewIkqExGwhTTCzT85v0g',
    appId: '1:776646365405:web:18f0bd64c063cda94a4b34',
    messagingSenderId: '776646365405',
    projectId: 'helpdisk-f8a08',
    authDomain: 'helpdisk-f8a08.firebaseapp.com',
    storageBucket: 'helpdisk-f8a08.firebasestorage.app',
    measurementId: 'G-1LV8952HD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcabHKYEGCEGaHv3Ghml9-ykigL1lU2tU',
    appId: '1:776646365405:android:35638a6cb2ba35ef4a4b34',
    messagingSenderId: '776646365405',
    projectId: 'helpdisk-f8a08',
    storageBucket: 'helpdisk-f8a08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuoAZORTFSzVtaII8fKvIR7KLWpYfjKTI',
    appId: '1:776646365405:ios:c5ca81417d70beec4a4b34',
    messagingSenderId: '776646365405',
    projectId: 'helpdisk-f8a08',
    storageBucket: 'helpdisk-f8a08.firebasestorage.app',
    iosBundleId: 'com.example.helpdesk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuoAZORTFSzVtaII8fKvIR7KLWpYfjKTI',
    appId: '1:776646365405:ios:c5ca81417d70beec4a4b34',
    messagingSenderId: '776646365405',
    projectId: 'helpdisk-f8a08',
    storageBucket: 'helpdisk-f8a08.firebasestorage.app',
    iosBundleId: 'com.example.helpdesk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqV-v1svhYUDRewIkqExGwhTTCzT85v0g',
    appId: '1:776646365405:web:9d9a78131bbb22a24a4b34',
    messagingSenderId: '776646365405',
    projectId: 'helpdisk-f8a08',
    authDomain: 'helpdisk-f8a08.firebaseapp.com',
    storageBucket: 'helpdisk-f8a08.firebasestorage.app',
    measurementId: 'G-FQK7DK4C72',
  );
}
